# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-04 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20200104_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='title',
        ),
        migrations.AddField(
            model_name='bike',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bike',
            name='price',
            field=models.DecimalField(decimal_places=2, default='100.00', max_digits=6),
        ),
    ]
